Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.hostname = "atlocalvm"
  config.vm.box_check_update = false
   
  config.vm.network "forwarded_port", guest: 3306, host: 3306

  config.vm.define "ATDB" do |t|
  end

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = false
    # Customize the amount of memory on the VM:
    vb.memory = "1024"
    vb.cpus = "1"
    # Let's have a common name.
    vb.name = "AT Local VM Env"
  end

  config.vm.provision "shell", path: "scripts/vagrant/vagrant_provision.sh"
  
end
